### ISSUE TITLE
Should we add ft_index tag in zim files?

### ISSUE THREAD

**Issue by automactic** [kiwix/mwoffliner#22]
**Should we add tag in zim files indicating whether thebook has embedded index?**
Now have nopic indicating zim file does not have pics, should the same be done for embedded index?

The benefit:
- User will be able to know if a book has index before downloading it (ft_index tag will also be in library.xml)

The disadvantage:
- redundant for book user already have (we can test for `/Z/fulltextIndex/xapian`, then we will know)
- become unnecessary if majority of the zim files in library.xml have index

**Comment by kelson42** [comment]
Will do it.

**Comment by kelson42** [comment]
I have modify zimwriterfs to add the tag _ftindex automatically with the ZIM has a fulltext index.
