### ISSUE TITLE
Articles in Vikidia zim files doesn't have id in headings

### ISSUE THREAD

**Issue by automactic** [kiwix/mwoffliner#24]
**Problem**:
In Vikidia zim files, h2, h3 elements doesn't have id. Table of content system needs id to scroll an element to viewport.

**Example**:
In vikidia_en_all_2016-09.zim, article European Union, header `<h2> Member countries </h2>` doesn't have id. Javascript couldn't scroll to this element if user select this header in table of contents.

**Comment by kelson42** [comment]
Is that a new problem?

**Comment by kelson42** [comment]
@automactic Have you fixed Kiwix for iOS to get the table of content working even if no "id' ? This is important.

**Comment by automactic** [comment]
I don't plan to implement another algorithm for no-id situation. So I might give an id to all children of `mw-content-text`. But I strongly suggest to fix this on the zim making side, so clients can be lazier.

**Comment by kelson42** [comment]
The "id" attribute is not mandatory in HTML and the HTML we have in ZIM files is not generated by us, but by the Mediawiki backend (in the case of Wikipedai). Kiwix should therefore not rely on it.

**Comment by kelson42** [comment]
I have open a bug on iOS side https://github.com/kiwix/iOS/issues/37
