### ISSUE TITLE
New landing pages for es, en and fr wikipedia

### ISSUE THREAD

**Issue by Popolechien** [kiwix/mwoffliner#26]
I've prepared dedicated, simpled landing pages for 
**Spanish wikipedia**
https://es.wikipedia.org/wiki/user:Popo_le_Chien/Kiwix
**English Wikipedia**
https://en.wikipedia.org/wiki/user:Popo_le_Chien/Kiwix
**French Wikipedia**
https://fr.wikipedia.org/wiki/user:Popo_le_Chien/Kiwix

**Comment by kelson42** [comment]
done https://github.com/kiwix/mwoffliner/compare/be855ee899...077a823430
