### ISSUE TITLE
Parameter 'url' must be a string, not undefined

### ISSUE THREAD

**Issue by qoolq** [kiwix/mwoffliner#27]
Steps to reproduce:
- Run Debian 8 amd64 network installer in a VirtualBox virtual machine
- Select "American" and/or "English" for all locale settings
- Select MATE for desktop
- Boot to new system, log in as the non-privileged user
- Enable passwordless sudo for group "sudo"
- Add non-privileged user created during installation to group "sudo"
- Change /etc/apt/sources.list to include only the "main" repository for the "stretch" release
- Disable screensaver so as to not make the system unresponsive while upgrading

```
    sudo apt-get update
    sudo apt-get dist-upgrade
    sudo reboot
```
- Log in as the non-privileged user

```
    sudo apt-get install build-essential module-assistant git redis-server redis-tools jpegoptim advancecomp gifsicle pngquant imagemagick curl liblzma-dev libmagic-dev zlib1g-dev libgumbo-dev libtool automake libicu-dev uuid uuid-dev libzim-dev
    sudo m-a prepare
```
- Mount VirtualBox guest additions image at /media/cdrom0

```
    cp -r /media/cdrom0 ~/
    sudo ~/cdrom0/VBoxLimuxAdditions.run
    sudo reboot
```
- Log in as the non-privileged user

```
    wget https://nodejs.org/download/release/v4.4.7/node-v4.4.7.tar.gz
    tar xf node-v4.4.7.tar.gz
    cd node-v4.4.7
    ./configure
    make
    sudo make install
    cd
    git clone https://github.com/kiwix/mwoffliner.git
    cd mwoffliner
    npm install
```
- Open /etc/redis/redis.conf and uncomment the unixsocket and unixsocketperm lines
- Change unixsocket to /dev/shm/redis.sock and unixsocketperm to 777

```
    sudo systemctl restart redis-server.service
    cd
    npm install parsoid
    cp ~/node_modules/parsoid/localsettings.js.example ~/node_modules/parsoid/localsettings.js
    ~/node_modules/parsoid/bin/server.js
```
- Leave the above server running and open a new terminal

```
    git clone https://github.com/wikimedia/openzim.git
    cd openzim/zimlib
    ./autogen.sh
    ./configure
    make
    cd
    wget http://download.kiwix.org/dev/xapian-core-1.4.1-git.tar.xz
    tar xf xapian-core-1.4.1-git.tar.xz
    cd xapian-core-1.4.0
    ./configure
    make
    sudo make install
    cd ~openzim/zimwriterfs
    ./autogen
    ./configure CXXFLAGS=-I../zimlib/include LDFLAGS=-L../zimlib/src/.libs
    make
    sudo make install
    cd
    mkdir wikis
    cd wikis
    mkdir puella-magi
    cd puella-magi
    ~/mwoffliner/mwoffliner.js --verbose --mwUrl="http://wiki.puella-magi.net/" --adminEmail="[email]" --mwWikiPath="" --mwApiPath="api.php" --parsoidUrl="http://localhost:8000"
```

Results in the following error:

```
Saving favicon.png...
Downloading http://wiki.puella-magi.net/api.php?action=query&meta=siteinfo&format=json...
TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:90:11)
    at Object.urlParse [as parse] (url.js:84:5)
    at /home/mediawiki/mwoffliner/mwoffliner.js:2435:26
    at /home/mediawiki/mwoffliner/mwoffliner.js:2193:6
    at /home/mediawiki/mwoffliner/node_modules/async/lib/async.js:676:51
    at /home/mediawiki/mwoffliner/node_modules/async/lib/async.js:726:13
    at /home/mediawiki/mwoffliner/node_modules/async/lib/async.js:52:16
    at /home/mediawiki/mwoffliner/node_modules/async/lib/async.js:264:21
    at /home/mediawiki/mwoffliner/node_modules/async/lib/async.js:44:16
    at /home/mediawiki/mwoffliner/node_modules/async/lib/async.js:723:17
```

**Comment by kelson42** [comment]
See also #10

**Comment by kelson42** [comment]
Currenlty mwoffliner runs with nodejs v4.2.6

**Comment by qoolq** [comment]
@kelson42 I was told in #Node.js that all v4.x.x versions of Node should be mutually compatible, and that this is most likely an issue with lines 2433-2435 trying to get "logo" from JSON and assuming that it exists when it might not exist.

**Comment by qoolq** [comment]
Yes, as suspected, [that wiki's siteinfo](http://wiki.puella-magi.net/api.php?action=query&meta=siteinfo&format=json) does not define "logo"

**Comment by kelson42** [comment]
@qoolq, Mediawiki has been released more than 5 years ago the 2011-07-18. Kind of hard to modify mwoffliner to support this. A solution might be to just specify a "--customZimFavicon" on the custom line, this should avoid checking the version which is online. Let me know if it works.

**Comment by kelson42** [comment]
I guess we wont fix this because this goes back to far in the past.
