### ISSUE TITLE
Generate zim files of PhET in Arabic, Chinese, German, Russian, Spanish and French

### ISSUE THREAD

**Issue by Popolechien** [kiwix/mwoffliner#37]
We only have the English version, but we should offer at least the next 5-6 largest Kiwix user bases.

**Comment by kelson42** [comment]
@Popolechien The idea was to generate one zim/app, providing a way to change the language. We had something working but the app was around 140MB big. The plan was to try to find wasy to optimize the solution to bring it <80MB.

**Comment by Popolechien** [comment]
@kelson42 this does not seem an easy path as far as UX goes. We must assume that not everyone speaks English and/or is savvy enough to look for a language selector (at least that's my takeaway from seeing the arabic feedback). Can we drop the app for the time being and focus on having 5 different zims?

**Comment by kelson42** [comment]
@Popolechien would that be good enough if the app just take the language of the system per default? I do not think the vision is to have one app per language, we should go in the direction of having one app which adapt to the language of the user.

**Comment by Popolechien** [comment]
@kelson42 For the app yes, fine by me, but my request was simply to generate additional zim files (for Kiwix proper, that is).

**Comment by kelson42** [comment]
@Popolechien Ok, this is tracked here https://github.com/kiwix/phet/issues/15
