### ISSUE TITLE
readme has insufficient information to install mwoffliner

### ISSUE THREAD

**Issue by tim-moody** [kiwix/mwoffliner#39]
"You need also to install all necessary nodejs "packages with "npm install" in this directory."

none are present or named.

"You need also a redis server correctly configured and listening to /dev/shm/redis.sock."

what constitutes 'correctly configured' is not mentioned.

**Comment by kelson42** [comment]
@tim-moody 
You just need to run "npm install", there is not package to give.
For Redis, you can configured it like you want, the only thing is that it has to listen to the right socket. (I will update the README for this).

**Comment by kelson42** [comment]
@tim-moody Let me know is something is still unclear.

**Comment by tim-moody** [comment]
npm install worked

hopefully I can get redis installed from the existing docs

**Comment by tim-moody** [comment]
adding (without any package name) to the readme would help
