### ISSUE TITLE
Change attribution wording at bottom of Wiki* pages

### ISSUE THREAD

**Issue by Popolechien** [kiwix/mwoffliner#48]
We currently have too many people complaining that the zim files are old because they get confused with the current wording "version of dd/mm/yyyy" (it is not clear that it actually is "last edited on dd/mm/yyyy").

Since we can't list authors but have a link to oldid, and based on Creative Commons' best practices could we replace the wording with 
"[Pagename] is licensed under a [Creative Commons - Attribution - Sharealike](https://creativecommons.org/licenses/by-sa/4.0/). Additional terms may apply for the media files."

Whereby [Pagename] links to the permanent link with oldid, and we don't indicate a date anymore (the link does that). 
Also: license terms link needs to be upgraded from 3.0 to [4.0](https://creativecommons.org/licenses/by-sa/4.0/).

**Comment by kelson42** [comment]
@Popolechien Better ? https://github.com/kiwix/mwoffliner/commit/17bcb79e40e9cc9e450659b99dae5bc5e3a7644c

**Comment by kelson42** [comment]
done
