### ISSUE TITLE
Problem with the February portable dumps in German

### ISSUE THREAD

**Issue by Popolechien** [kiwix/mwoffliner#55]
From OTRS: 

Hi,

there seems to be a problem with the february portable dumps
of the german wikipedia, see

http://download.kiwix.org/portable/wikipedia/?C=M;O=D

The non-portable, zim versions in zim/ directory are fine, though.

Because I suspect that they have been automatically generated
by a cron job or similar, there might be a bug in the toolchain and
hence some probability that the next dump may fail as well (which
is why I'm writing this..)

Regards,
Jim

**Comment by kelson42** [comment]
Fixed
